2023-07-14 12:42:56,236 DEBUG (decos.py) Функция main c параметрами (), {}. Вызов из модуля __main__. 
2023-07-14 12:45:06,200 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-14 12:45:06,201 DEBUG (server.py) Аргументы успешно загружены
2023-07-14 12:45:06,202 DEBUG (decos.py) Функция create_arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__. 
2023-07-14 12:45:06,411 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-14 12:45:20,917 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 39710)
2023-07-14 12:45:38,149 DEBUG (decos.py) Функция main c параметрами (), {}. Вызов из модуля __main__. 
2023-07-14 17:48:18,997 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-14 17:48:19,013 DEBUG (server.py) Аргументы успешно загружены
2023-07-14 17:48:19,013 DEBUG (decos.py) Функция create_arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__. 
2023-07-14 17:48:19,188 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-14 17:48:50,068 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 47824)
2023-07-14 18:13:46,074 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-14 18:13:46,076 DEBUG (server.py) Аргументы успешно загружены
2023-07-14 18:13:46,076 DEBUG (decos.py) Функция create_arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__. 
2023-07-14 18:13:46,566 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-14 18:14:20,162 DEBUG (decos.py) Функция main c параметрами (), {}. Вызов из модуля __main__. 
2023-07-14 18:14:24,668 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-14 18:14:24,668 DEBUG (server.py) Аргументы успешно загружены
2023-07-14 18:14:24,668 DEBUG (decos.py) Функция create_arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__. 
2023-07-14 18:14:24,747 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-14 18:14:40,593 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 60332)
2023-07-14 18:24:06,430 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 43328)
2023-07-14 18:24:06,430 DEBUG (decos.py) Функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60332)>,), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 18:24:06,431 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689340480.6294613, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-14 18:24:06,431 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-14 18:24:06,449 DEBUG (core.py) Correct username, starting passwd check
2023-07-14 18:24:06,460 DEBUG (core.py) Auth message = {'response': 511, 'bin': '71f25bad681881557ebbf0c141b3d1d5783c2e95416ccea8ffe9f67eb695b51c06b4e6865cdfde76591bd446aacc7ad34d827635ef136cb47b8a7f81a1971f87'}
2023-07-14 18:24:06,461 DEBUG (decos.py) Функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>, {'response': 511, 'bin': '71f25bad681881557ebbf0c141b3d1d5783c2e95416ccea8ffe9f67eb695b51c06b4e6865cdfde76591bd446aacc7ad34d827635ef136cb47b8a7f81a1971f87'}), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 18:24:06,461 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 57, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 14, in log_writer
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/prgm_utils.py", line 22, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-14 18:24:06,489 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a553b29e0> отключился от сервера
2023-07-14 18:26:36,369 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-14 18:26:36,370 DEBUG (server.py) Аргументы успешно загружены
2023-07-14 18:26:36,370 DEBUG (decos.py) Функция create_arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__. 
2023-07-14 18:26:36,467 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-14 18:27:03,378 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 50806)
2023-07-14 18:29:04,705 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 53024)
2023-07-14 18:29:04,706 DEBUG (decos.py) Функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50806)>,), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 18:29:04,706 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689341223.4071069, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-14 18:29:04,706 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-14 18:29:04,720 DEBUG (core.py) Correct username, starting passwd check
2023-07-14 18:29:04,725 DEBUG (core.py) Auth message = {'response': 511, 'bin': '257492f68cfd3fe9554c547c631e678bf6b49f76dc8d550ba019b2a0ebd410c4b1c8ae303ffc14b15efc3abfd71fd7e6ab6e204badc09a11926570925cffcad9'}
2023-07-14 18:29:04,725 DEBUG (decos.py) Функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>, {'response': 511, 'bin': '257492f68cfd3fe9554c547c631e678bf6b49f76dc8d550ba019b2a0ebd410c4b1c8ae303ffc14b15efc3abfd71fd7e6ab6e204badc09a11926570925cffcad9'}), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 18:29:04,726 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 57, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 14, in log_writer
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/prgm_utils.py", line 22, in get_message
    return response
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-14 18:29:04,728 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7fe003ba33a0> отключился от сервера
2023-07-14 18:38:58,989 DEBUG (decos.py) Функция main c параметрами (), {}. Вызов из модуля __main__. 
2023-07-14 18:39:07,993 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 18:39:15,270 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 18:41:03,033 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 18:41:10,577 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 19:09:40,502 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 19:11:17,677 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 19:11:33,791 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.prgm_utils. 
2023-07-14 19:14:41,109 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.utils. 
2023-07-14 19:19:26,684 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.utils. 
2023-07-14 19:23:31,611 DEBUG (decos.py) Функция get_message c параметрами (), {}. Вызов из модуля common.utils. 
2023-07-14 19:27:17,358 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-14 19:27:17,359 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-14 19:27:17,359 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-14 19:27:17,360 DEBUG (server.py) Аргументы успешно загружены
2023-07-14 19:27:17,432 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-14 19:27:43,011 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 35322)
2023-07-14 19:31:17,379 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-14 19:31:17,379 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-14 19:31:17,379 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-14 19:31:17,380 DEBUG (server.py) Аргументы успешно загружены
2023-07-14 19:31:17,469 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-14 19:31:27,547 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 37696)
2023-07-14 19:34:25,272 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 48136)
2023-07-14 19:34:25,272 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 37696)>,) , {}. Вызов из модуля common.utils
2023-07-14 19:34:25,273 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689345087.5577447, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-14 19:34:25,273 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-14 19:34:25,280 DEBUG (core.py) Correct username, starting passwd check
2023-07-14 19:34:25,281 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'c139b6cacbda31412b2568ced428198a0341569f6cdf4577b48623ca6492af559b17908f4814b9b233b5f41be2be11734a66a2a54307a600a133b820818a1021'}
2023-07-14 19:34:25,281 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 37696)>, {'response': 511, 'bin': 'c139b6cacbda31412b2568ced428198a0341569f6cdf4577b48623ca6492af559b17908f4814b9b233b5f41be2be11734a66a2a54307a600a133b820818a1021'}) , {}. Вызов из модуля common.utils
2023-07-14 19:34:25,281 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-14 19:34:25,281 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 20, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-14 19:34:25,282 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7fccbf3b3d60> отключился от сервера
2023-07-14 19:35:02,969 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 40100)
2023-07-14 19:35:02,970 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48136)>,) , {}. Вызов из модуля common.utils
2023-07-14 19:35:02,970 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689345265.2847118, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-14 19:35:02,971 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-14 19:35:02,973 DEBUG (core.py) Correct username, starting passwd check
2023-07-14 19:35:02,975 DEBUG (core.py) Auth message = {'response': 511, 'bin': '4f9b2f0732d14ef7c3fa23fb60ff771bb65f9856f17ccf7d20e2a5ccefb22f9c77ffa19794b05dbcd2eb25447ae5ca3833dd6584710d58499e329ce175cad80e'}
2023-07-14 19:35:02,976 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48136)>, {'response': 511, 'bin': '4f9b2f0732d14ef7c3fa23fb60ff771bb65f9856f17ccf7d20e2a5ccefb22f9c77ffa19794b05dbcd2eb25447ae5ca3833dd6584710d58499e329ce175cad80e'}) , {}. Вызов из модуля common.utils
2023-07-14 19:35:02,976 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-14 19:35:02,977 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 20, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-14 19:35:02,977 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7fccbf3b2680> отключился от сервера
2023-07-15 11:41:23,098 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-15 11:41:23,107 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-15 11:41:23,107 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-15 11:41:23,107 DEBUG (server.py) Аргументы успешно загружены
2023-07-15 11:41:23,190 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-15 11:42:25,747 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 51238)
2023-07-15 11:42:42,758 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 44996)
2023-07-15 11:42:42,758 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51238)>,) , {}. Вызов из модуля common.utils
2023-07-15 11:42:42,758 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689403345.7803934, 'user': {'account_name': 'test', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3DPhQxbzc/rnvdAsWcUe\nyNXW/sR8b/nIjNohjBd/z4jXpHyBTFzH52DMXImNFHJ189uPOOU/Fror2FWzxG91\nkcCmOzgpNDsv+J09w9LCi1h9d716eqq5w6QX5yJtnVuUxNer/yCkCrakceIIQdiR\nhkB4uRdeqPgAKHG8/XIMjHD405QuzWmiPFuO8cgpv8MshP9XpLCRi1VTSY0aGrt8\nO+sXD8emhIUcuQsIUipVRoOGxAu8RUdDxxg+R/ol2eqh9mdU9adfTxDE1Lt1j+Ea\nAaacxoDoyAMgv8ktwjeoi8opy9SAHu5+yrs8ySs2Ra0/CGmvoDdVQk+LrjnAfV3P\nSQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 11:42:42,759 DEBUG (core.py) Start auth process for {'account_name': 'test', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3DPhQxbzc/rnvdAsWcUe\nyNXW/sR8b/nIjNohjBd/z4jXpHyBTFzH52DMXImNFHJ189uPOOU/Fror2FWzxG91\nkcCmOzgpNDsv+J09w9LCi1h9d716eqq5w6QX5yJtnVuUxNer/yCkCrakceIIQdiR\nhkB4uRdeqPgAKHG8/XIMjHD405QuzWmiPFuO8cgpv8MshP9XpLCRi1VTSY0aGrt8\nO+sXD8emhIUcuQsIUipVRoOGxAu8RUdDxxg+R/ol2eqh9mdU9adfTxDE1Lt1j+Ea\nAaacxoDoyAMgv8ktwjeoi8opy9SAHu5+yrs8ySs2Ra0/CGmvoDdVQk+LrjnAfV3P\nSQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 11:42:42,764 DEBUG (core.py) Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован'}
2023-07-15 11:42:42,764 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51238)>, {'response': 400, 'error': 'Пользователь не зарегистрирован'}) , {}. Вызов из модуля common.utils
2023-07-15 11:43:38,804 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 44316)
2023-07-15 11:43:38,804 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44996)>,) , {}. Вызов из модуля common.utils
2023-07-15 11:43:38,804 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689403362.7694564, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 11:43:38,804 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 11:43:38,805 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 11:43:38,807 DEBUG (core.py) Auth message = {'response': 511, 'bin': '7b3bb7e10ad31638dc96b8d34901d126076f13e59049528ca3e96464487fba34b9a4b354353d129a5be1d35d94663263e52b7efd2f17d7823b14137823aa6450'}
2023-07-15 11:43:38,807 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44996)>, {'response': 511, 'bin': '7b3bb7e10ad31638dc96b8d34901d126076f13e59049528ca3e96464487fba34b9a4b354353d129a5be1d35d94663263e52b7efd2f17d7823b14137823aa6450'}) , {}. Вызов из модуля common.utils
2023-07-15 11:43:38,807 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 11:43:38,807 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 20, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 11:43:38,809 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f1dd1ab2e60> отключился от сервера
2023-07-15 11:53:39,005 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-15 11:53:39,006 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-15 11:53:39,006 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-15 11:53:39,007 DEBUG (server.py) Аргументы успешно загружены
2023-07-15 11:53:39,084 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-15 11:53:51,088 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 39872)
2023-07-15 11:56:54,578 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 48102)
2023-07-15 11:56:54,579 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 39872)>,) , {}. Вызов из модуля common.utils
2023-07-15 11:56:54,579 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689404031.1222286, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 11:56:54,580 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 11:56:54,595 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 11:56:54,599 DEBUG (core.py) Auth message = {'response': 511, 'bin': '5cab6d9f75ed7766e46eeaf62ae87d6379a8121378d0e5f6eddaa9957af577acfe6d9e556f25a942bb8ed3d41592d0ea6075513941a091d84cf788cdc3d4f30f'}
2023-07-15 11:56:54,600 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 39872)>, {'response': 511, 'bin': '5cab6d9f75ed7766e46eeaf62ae87d6379a8121378d0e5f6eddaa9957af577acfe6d9e556f25a942bb8ed3d41592d0ea6075513941a091d84cf788cdc3d4f30f'}) , {}. Вызов из модуля common.utils
2023-07-15 11:56:54,600 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 11:56:54,601 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 11:56:54,603 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a2080> отключился от сервера
2023-07-15 11:59:52,752 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 52600)
2023-07-15 11:59:52,752 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48102)>,) , {}. Вызов из модуля common.utils
2023-07-15 11:59:52,753 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689404214.6118412, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 11:59:52,753 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 11:59:52,756 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 11:59:52,758 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'bf22d2ee1fa949bd9209424b8b5717f72690abe64eec8dc2df6154339a9ccd839faa108a13edb0b936ed2ef92601802d079f41c741d01d58e91c9d56eb38ad93'}
2023-07-15 11:59:52,758 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48102)>, {'response': 511, 'bin': 'bf22d2ee1fa949bd9209424b8b5717f72690abe64eec8dc2df6154339a9ccd839faa108a13edb0b936ed2ef92601802d079f41c741d01d58e91c9d56eb38ad93'}) , {}. Вызов из модуля common.utils
2023-07-15 11:59:52,759 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 11:59:52,759 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 11:59:52,760 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a1180> отключился от сервера
2023-07-15 12:02:44,133 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 34346)
2023-07-15 12:02:44,134 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52600)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:02:44,134 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689404392.7855067, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:02:44,134 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:02:44,135 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:02:44,136 DEBUG (core.py) Auth message = {'response': 511, 'bin': '4dfbff710010b42ef9e4cd967482fe99f65f1174483935745c443bfccabedbeaac8c766b2f7ca90c0f70a53ab937e762b79a85d799608c2a6294399699a05bb2'}
2023-07-15 12:02:44,136 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52600)>, {'response': 511, 'bin': '4dfbff710010b42ef9e4cd967482fe99f65f1174483935745c443bfccabedbeaac8c766b2f7ca90c0f70a53ab937e762b79a85d799608c2a6294399699a05bb2'}) , {}. Вызов из модуля common.utils
2023-07-15 12:02:44,137 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:02:44,137 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:02:44,137 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a3880> отключился от сервера
2023-07-15 12:04:07,371 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 45654)
2023-07-15 12:04:07,372 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 34346)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:04:07,372 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689404564.152454, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:04:07,372 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:04:07,375 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:04:07,377 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'cfe1ce0f4f1bda9ea32a01cbf3b6b707fa5a61c1fce8eb616e0a08d29d843d6c65d6c22c281dc2e9b3b89e7f75f8786224d89e742b3d5ceb89cf4e46bd2594a6'}
2023-07-15 12:04:07,377 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 34346)>, {'response': 511, 'bin': 'cfe1ce0f4f1bda9ea32a01cbf3b6b707fa5a61c1fce8eb616e0a08d29d843d6c65d6c22c281dc2e9b3b89e7f75f8786224d89e742b3d5ceb89cf4e46bd2594a6'}) , {}. Вызов из модуля common.utils
2023-07-15 12:04:07,377 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:04:07,377 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:04:07,377 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a2080> отключился от сервера
2023-07-15 12:05:26,033 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 39146)
2023-07-15 12:05:26,033 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 45654)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:05:26,033 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689404647.384255, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:05:26,034 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:05:26,035 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:05:26,037 DEBUG (core.py) Auth message = {'response': 511, 'bin': '00aaba84e913c6b1e021f06b9f4bb2371b3dae420e85e27699aa619bd50fc0a310faad6ca54551949232870e6edd837cba1b5193daad798de658f15979182d59'}
2023-07-15 12:05:26,037 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 45654)>, {'response': 511, 'bin': '00aaba84e913c6b1e021f06b9f4bb2371b3dae420e85e27699aa619bd50fc0a310faad6ca54551949232870e6edd837cba1b5193daad798de658f15979182d59'}) , {}. Вызов из модуля common.utils
2023-07-15 12:05:26,037 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:05:26,037 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:05:26,038 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9cf3a0> отключился от сервера
2023-07-15 12:18:49,577 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 48592)
2023-07-15 12:18:49,578 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 39146)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:18:49,578 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689404726.0446699, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:18:49,578 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:18:49,580 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:18:49,581 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'd8d9015fb1183af434993d043480210560bf4e63f4cb3ea7aab3ae153b52a4bd555239efc1645f2475e099ce1d2af1a907dbb0aba791a73242d77154e37266fd'}
2023-07-15 12:18:49,581 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 39146)>, {'response': 511, 'bin': 'd8d9015fb1183af434993d043480210560bf4e63f4cb3ea7aab3ae153b52a4bd555239efc1645f2475e099ce1d2af1a907dbb0aba791a73242d77154e37266fd'}) , {}. Вызов из модуля common.utils
2023-07-15 12:18:49,581 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:18:49,582 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    json_response = encoded_response.decode(ENCODING)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:18:49,583 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a3880> отключился от сервера
2023-07-15 12:21:53,601 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 44832)
2023-07-15 12:21:53,601 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48592)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:21:53,601 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689405529.58967, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:21:53,602 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:21:53,604 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:21:53,606 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'ff6995f96644e6ed8bcb5803570ec7eb3ab4131690be01d12968581823bea5526e685cd82b61c76c3d100e0b749e0f7dea0a8ce7cae50e6ec72ed76a7c871295'}
2023-07-15 12:21:53,606 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48592)>, {'response': 511, 'bin': 'ff6995f96644e6ed8bcb5803570ec7eb3ab4131690be01d12968581823bea5526e685cd82b61c76c3d100e0b749e0f7dea0a8ce7cae50e6ec72ed76a7c871295'}) , {}. Вызов из модуля common.utils
2023-07-15 12:21:53,606 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:21:53,606 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    json_response = encoded_response.decode(ENCODING)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:21:53,606 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a3b753160> отключился от сервера
2023-07-15 12:36:04,326 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 59414)
2023-07-15 12:36:04,327 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44832)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:36:04,327 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689405713.6137247, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:36:04,328 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:36:04,330 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:36:04,332 DEBUG (core.py) Auth message = {'response': 511, 'bin': '4cb1c4fb8f2a00c9726fe5233ffd23700302bb89120c91b5fcd8069ba1e31ed3912af525777d67a314bb015b66cc7fa61e0b509aa2cb18f5862906bb2c86a280'}
2023-07-15 12:36:04,333 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44832)>, {'response': 511, 'bin': '4cb1c4fb8f2a00c9726fe5233ffd23700302bb89120c91b5fcd8069ba1e31ed3912af525777d67a314bb015b66cc7fa61e0b509aa2cb18f5862906bb2c86a280'}) , {}. Вызов из модуля common.utils
2023-07-15 12:36:04,333 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:36:04,333 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    json_response = encoded_response.decode(ENCODING)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:36:04,334 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9cf3a0> отключился от сервера
2023-07-15 12:39:08,190 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 34194)
2023-07-15 12:39:08,191 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59414)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:39:08,191 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    json_response = encoded_response.decode(ENCODING)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 557 (char 556)
2023-07-15 12:39:08,191 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a3880> отключился от сервера
2023-07-15 12:40:54,327 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 51444)
2023-07-15 12:40:54,327 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 34194)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:40:54,328 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    json_response = encoded_response.decode(ENCODING)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 558 (char 557)
2023-07-15 12:40:54,328 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a3b753160> отключился от сервера
2023-07-15 12:41:54,432 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 41552)
2023-07-15 12:41:54,432 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51444)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:41:54,433 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689406854.3627732, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:41:54,433 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:41:54,435 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:41:54,437 DEBUG (core.py) Auth message = {'response': 511, 'bin': '1cffe8512ff551f292e90a32568c91de124cb91c015e4c1efd5044a92c7146dd83802d5fc9b5689da8bfed04980b1357c5eb83d15116de223839b3eba514c748'}
2023-07-15 12:41:54,438 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51444)>, {'response': 511, 'bin': '1cffe8512ff551f292e90a32568c91de124cb91c015e4c1efd5044a92c7146dd83802d5fc9b5689da8bfed04980b1357c5eb83d15116de223839b3eba514c748'}) , {}. Вызов из модуля common.utils
2023-07-15 12:41:54,438 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:41:54,438 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    json_response = encoded_response.decode(ENCODING)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:41:54,439 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9cf3a0> отключился от сервера
2023-07-15 12:43:13,910 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 35160)
2023-07-15 12:43:13,911 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 41552)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:43:13,911 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    json_response = encoded_response.decode(ENCODING)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 558 (char 557)
2023-07-15 12:43:13,913 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a3880> отключился от сервера
2023-07-15 12:44:58,663 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 40414)
2023-07-15 12:44:58,663 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 35160)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:44:58,664 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689406993.9219534, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:44:58,664 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:44:58,668 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:44:58,670 DEBUG (core.py) Auth message = {'response': 511, 'bin': '0b4140cbf558a18e1759eb7adb38fc968ea14493ca492bea63a5e3d3c0f2a45bf0157b0925a39eeb842ab2dda73d2bb6908aaf3d70e29d03ff7146d1870eac75'}
2023-07-15 12:44:58,671 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 35160)>, {'response': 511, 'bin': '0b4140cbf558a18e1759eb7adb38fc968ea14493ca492bea63a5e3d3c0f2a45bf0157b0925a39eeb842ab2dda73d2bb6908aaf3d70e29d03ff7146d1870eac75'}) , {}. Вызов из модуля common.utils
2023-07-15 12:44:58,671 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:44:58,672 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    if isinstance(encoded_response, bytes):
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:44:58,673 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a3b753160> отключился от сервера
2023-07-15 12:46:07,726 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 37438)
2023-07-15 12:46:07,726 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 40414)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:46:07,727 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689407098.6991382, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:46:07,727 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:46:07,730 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:46:07,733 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'b74a5fb1fd18124b83064ef271fa5a50dd2300167e9d68543f946e2f2c4188e33f7963385545e3285b2372b7c0452045d783988adf0541d881b657a91a57604a'}
2023-07-15 12:46:07,733 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 40414)>, {'response': 511, 'bin': 'b74a5fb1fd18124b83064ef271fa5a50dd2300167e9d68543f946e2f2c4188e33f7963385545e3285b2372b7c0452045d783988adf0541d881b657a91a57604a'}) , {}. Вызов из модуля common.utils
2023-07-15 12:46:07,734 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:46:07,734 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print(encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:46:07,736 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9cf3a0> отключился от сервера
2023-07-15 12:47:01,606 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 51842)
2023-07-15 12:47:01,606 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 37438)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:47:01,606 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689407167.7718253, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:47:01,606 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:47:01,608 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:47:01,609 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'e7a2e38ad05f194ca5b5c0706b07f7907946b7c89fe591f01cc9ccfe0ec76ae40a8c01fb2a13ebe3991bdc55b6eb0d302406ddccddc511841b003cc99138f2a9'}
2023-07-15 12:47:01,609 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 37438)>, {'response': 511, 'bin': 'e7a2e38ad05f194ca5b5c0706b07f7907946b7c89fe591f01cc9ccfe0ec76ae40a8c01fb2a13ebe3991bdc55b6eb0d302406ddccddc511841b003cc99138f2a9'}) , {}. Вызов из модуля common.utils
2023-07-15 12:47:01,609 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:47:01,610 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print(encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:47:01,610 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a3880> отключился от сервера
2023-07-15 12:49:55,566 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 41784)
2023-07-15 12:49:55,566 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51842)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:49:55,566 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689407221.6293092, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:49:55,567 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:49:55,569 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:49:55,571 DEBUG (core.py) Auth message = {'response': 511, 'bin': '67c266d767477cfd742cfcf303c466be289717b6f405c429a4f4544822c8f7258cd3534471e988aba7cc3fbcba6b57d74052a7bd3547e52135ba9d9897eecf7b'}
2023-07-15 12:49:55,571 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51842)>, {'response': 511, 'bin': '67c266d767477cfd742cfcf303c466be289717b6f405c429a4f4544822c8f7258cd3534471e988aba7cc3fbcba6b57d74052a7bd3547e52135ba9d9897eecf7b'}) , {}. Вызов из модуля common.utils
2023-07-15 12:49:55,571 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:49:55,571 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print(encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:49:55,571 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a3b753160> отключился от сервера
2023-07-15 12:52:28,807 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 45958)
2023-07-15 12:52:28,808 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 41784)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:52:28,808 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689407395.5780997, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:52:28,808 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:52:28,809 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:52:28,810 DEBUG (core.py) Auth message = {'response': 511, 'bin': '0784a3a92bdcb335cc0a277b3d9faf9fe86b7da5d0540a1cdadb82d297c56802c4c7fc2b0efb21392bba364ea091742134d362a58cf2a62bf9b846a1ad6d2831'}
2023-07-15 12:52:28,810 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 41784)>, {'response': 511, 'bin': '0784a3a92bdcb335cc0a277b3d9faf9fe86b7da5d0540a1cdadb82d297c56802c4c7fc2b0efb21392bba364ea091742134d362a58cf2a62bf9b846a1ad6d2831'}) , {}. Вызов из модуля common.utils
2023-07-15 12:52:28,810 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:52:28,810 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print(encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:52:28,811 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9cf3a0> отключился от сервера
2023-07-15 12:57:56,150 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 48222)
2023-07-15 12:57:56,150 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 45958)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:57:56,150 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689407548.8258386, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:57:56,150 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:57:56,151 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:57:56,152 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'eed7c30315bf6670d4f7caaa4d7516d48ae1acd35f6672cefaeedcdce13d39f0c22c291f966580e6869af4b35bff5a208c0de1e45a4f90b433da481b3f634d23'}
2023-07-15 12:57:56,152 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 45958)>, {'response': 511, 'bin': 'eed7c30315bf6670d4f7caaa4d7516d48ae1acd35f6672cefaeedcdce13d39f0c22c291f966580e6869af4b35bff5a208c0de1e45a4f90b433da481b3f634d23'}) , {}. Вызов из модуля common.utils
2023-07-15 12:57:56,153 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:57:56,153 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print('recv - ',encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:57:56,153 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a3880> отключился от сервера
2023-07-15 12:58:39,224 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 52974)
2023-07-15 12:58:39,225 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48222)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:58:39,226 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689407876.1695857, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 12:58:39,226 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 12:58:39,229 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 12:58:39,230 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'c8db52b178a280812ec12d52d417523e2766b5b0469747e5caae44683a02f6e5a89e3fde02ac1ecff19f67e6b8171844191c64b17968e3860bf4535905b5b33c'}
2023-07-15 12:58:39,230 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48222)>, {'response': 511, 'bin': 'c8db52b178a280812ec12d52d417523e2766b5b0469747e5caae44683a02f6e5a89e3fde02ac1ecff19f67e6b8171844191c64b17968e3860bf4535905b5b33c'}) , {}. Вызов из модуля common.utils
2023-07-15 12:58:39,230 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 12:58:39,231 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print('recv - ', encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 12:58:39,231 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a3b753160> отключился от сервера
2023-07-15 13:01:44,305 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 40792)
2023-07-15 13:01:44,305 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52974)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:01:44,305 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689407919.237508, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 13:01:44,306 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 13:01:44,307 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 13:01:44,309 DEBUG (core.py) Auth message = {'response': 511, 'bin': '28ae1af3645a1b0c2933f5162f678c5164d319f275228d8e07e03ed6d27555ac7de8cbb2a6778510da62487121aeffec62139cd946113440ac293351cb9041f3'}
2023-07-15 13:01:44,309 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52974)>, {'response': 511, 'bin': '28ae1af3645a1b0c2933f5162f678c5164d319f275228d8e07e03ed6d27555ac7de8cbb2a6778510da62487121aeffec62139cd946113440ac293351cb9041f3'}) , {}. Вызов из модуля common.utils
2023-07-15 13:01:44,310 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:01:44,310 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print('recv - ', encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 13:01:44,310 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9cf3a0> отключился от сервера
2023-07-15 13:03:39,824 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 37408)
2023-07-15 13:03:39,824 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 40792)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:03:39,824 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689408104.3177598, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 13:03:39,824 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 13:03:39,826 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 13:03:39,828 DEBUG (core.py) Auth message = {'response': 511, 'bin': '6a15b5536893b58dea3f1dcc75912b2dacd066cbb74a667aa4ece52b8935002c3b980a36527f9927d11376610686ccb98eab36d4281ebb2179035aa05135a7bb'}
2023-07-15 13:03:39,828 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 40792)>, {'response': 511, 'bin': '6a15b5536893b58dea3f1dcc75912b2dacd066cbb74a667aa4ece52b8935002c3b980a36527f9927d11376610686ccb98eab36d4281ebb2179035aa05135a7bb'}) , {}. Вызов из модуля common.utils
2023-07-15 13:03:39,829 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:03:39,829 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print('recv - ', encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 13:03:39,830 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a3880> отключился от сервера
2023-07-15 13:06:49,181 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 42142)
2023-07-15 13:06:49,181 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 37408)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:06:49,182 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689408219.857603, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 13:06:49,182 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 13:06:49,185 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 13:06:49,188 DEBUG (core.py) Auth message = {'response': 511, 'bin': '08eb7a8157676d6f031c5b944e34f45655219c06a0e3e7c9d706c308734615c5e715bb38f2916cb8d0570f338ce4ff2f5733dc66ddcb016624164968b13bc0e4'}
2023-07-15 13:06:49,188 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 37408)>, {'response': 511, 'bin': '08eb7a8157676d6f031c5b944e34f45655219c06a0e3e7c9d706c308734615c5e715bb38f2916cb8d0570f338ce4ff2f5733dc66ddcb016624164968b13bc0e4'}) , {}. Вызов из модуля common.utils
2023-07-15 13:06:49,189 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:06:49,190 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print('recv - ', encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 13:06:49,190 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a3b753160> отключился от сервера
2023-07-15 13:07:33,203 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 48136)
2023-07-15 13:07:33,203 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 42142)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:07:33,203 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689408409.218468, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 13:07:33,204 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 13:07:33,205 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 13:07:33,206 DEBUG (core.py) Auth message = {'response': 511, 'bin': '0b970fa51f146462bfc8a8575fc9d2b06fde5be629caa23821a5332f8a73801dde414e494cc4d6090e9c06cafbee7401b7da6a059eb87b9d540d23362842d2fd'}
2023-07-15 13:07:33,206 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 42142)>, {'response': 511, 'bin': '0b970fa51f146462bfc8a8575fc9d2b06fde5be629caa23821a5332f8a73801dde414e494cc4d6090e9c06cafbee7401b7da6a059eb87b9d540d23362842d2fd'}) , {}. Вызов из модуля common.utils
2023-07-15 13:07:33,206 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:07:33,207 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print('recv - ', encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 13:07:33,207 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9cf3a0> отключился от сервера
2023-07-15 13:08:37,525 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 46368)
2023-07-15 13:08:37,526 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48136)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:08:37,526 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689408453.2260656, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 13:08:37,526 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 13:08:37,529 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 13:08:37,531 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'acf9f6e313bb753a42a0d3aaa21843673b780ea75a129d6a137a16313130b85d739cc2351d417de5eb51e573ce2067d6358eef6307f93207a72cca0659f4cb68'}
2023-07-15 13:08:37,531 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 48136)>, {'response': 511, 'bin': 'acf9f6e313bb753a42a0d3aaa21843673b780ea75a129d6a137a16313130b85d739cc2351d417de5eb51e573ce2067d6358eef6307f93207a72cca0659f4cb68'}) , {}. Вызов из модуля common.utils
2023-07-15 13:08:37,532 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:08:37,532 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print('recv - ', encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 13:08:37,533 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a3880> отключился от сервера
2023-07-15 13:10:25,194 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 57120)
2023-07-15 13:10:25,194 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 46368)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:10:25,194 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689408517.5594375, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-15 13:10:25,195 DEBUG (core.py) Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-15 13:10:25,196 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 13:10:25,197 DEBUG (core.py) Auth message = {'response': 511, 'bin': '372ac572120beda2b66e819b54ba65d9275123ed5ecf55178418cc69d13a8ac2449cd7384fcf52573901ab51133ecaef891862845fea2030450fe2e912941dc7'}
2023-07-15 13:10:25,198 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 46368)>, {'response': 511, 'bin': '372ac572120beda2b66e819b54ba65d9275123ed5ecf55178418cc69d13a8ac2449cd7384fcf52573901ab51133ecaef891862845fea2030450fe2e912941dc7'}) , {}. Вызов из модуля common.utils
2023-07-15 13:10:25,198 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:10:25,198 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    print('recv - ', encoded_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 13:10:25,199 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a3b753160> отключился от сервера
2023-07-15 13:16:10,217 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 39658)
2023-07-15 13:16:10,218 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57120)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:16:10,218 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689408625.223608, 'user': {'account_name': 'test1'}}
2023-07-15 13:16:10,219 DEBUG (core.py) Start auth process for {'account_name': 'test1'}
2023-07-15 13:16:10,221 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 13:16:10,222 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'dbc4636051a6340653ab44ec1629e37e385fdfb0b9da5422997138257ff8d4ed1169f2a2d71086ab2f782ac442a5123ada9ea80cf82fd03854219029578c0385'}
2023-07-15 13:16:10,222 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57120)>, {'response': 511, 'bin': 'dbc4636051a6340653ab44ec1629e37e385fdfb0b9da5422997138257ff8d4ed1169f2a2d71086ab2f782ac442a5123ada9ea80cf82fd03854219029578c0385'}) , {}. Вызов из модуля common.utils
2023-07-15 13:16:10,222 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:16:10,222 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    if isinstance(encoded_response, bytes):
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 13:16:10,223 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9cf3a0> отключился от сервера
2023-07-15 13:17:54,223 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>,) , {}. Вызов из модуля __main__
2023-07-15 13:24:01,389 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 44544)
2023-07-15 13:24:01,389 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 44544), raddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля __main__
2023-07-15 13:24:01,389 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 39658)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:24:01,389 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689408970.229609, 'user': {'account_name': 'test1'}}
2023-07-15 13:24:01,389 DEBUG (core.py) Start auth process for {'account_name': 'test1'}
2023-07-15 13:24:01,390 DEBUG (core.py) Correct username, starting passwd check
2023-07-15 13:24:01,391 DEBUG (core.py) Auth message = {'response': 511, 'bin': 'e1b29c98938d644665e07c9cac20c065c33e9211e7c16672f8905e3c6d257c9faaddb20ee049567889eb95af45a184a968824a6f2ff622533acdcddb20090453'}
2023-07-15 13:24:01,391 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 39658)>, {'response': 511, 'bin': 'e1b29c98938d644665e07c9cac20c065c33e9211e7c16672f8905e3c6d257c9faaddb20ee049567889eb95af45a184a968824a6f2ff622533acdcddb20090453'}) , {}. Вызов из модуля common.utils
2023-07-15 13:24:01,391 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-15 13:24:01,391 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 75, in run
    for client_with_message in recv_data:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 153, in parse_client_message
    and USER in message:
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 305, in authorize_user
    try:
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-15 13:24:01,392 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f8a5e9a3880> отключился от сервера
2023-07-16 10:55:32,274 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 10:55:32,297 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 10:55:32,297 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-16 10:55:32,300 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 10:55:32,629 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 10:57:52,788 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 10:57:52,788 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 10:57:52,788 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-16 10:57:52,789 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 10:57:52,872 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 10:58:03,591 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 36678)
2023-07-16 10:58:40,694 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 38022)
2023-07-16 10:58:40,694 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 38022), raddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля __main__
2023-07-16 10:58:40,694 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 36678)>,) , {}. Вызов из модуля common.utils
2023-07-16 10:58:40,694 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689487083.6258223, 'user': {'account_name': 'test2'}}
2023-07-16 10:58:40,694 DEBUG (core.py) Start auth process for {'account_name': 'test2'}
2023-07-16 10:58:40,701 DEBUG (core.py) Correct username, starting passwd check
2023-07-16 10:58:40,704 DEBUG (core.py) Auth message = {'response': 511, 'bin': '73518f75871a72605b45bae5ab3fa55401febaca4b4042c2a58681e7032d5b38a2bee6298c5d16ba5f6b91d04cdbf6482b4376d789b7a35cc3b33d597627bdf2'}
2023-07-16 10:58:40,704 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 36678)>, {'response': 511, 'bin': '73518f75871a72605b45bae5ab3fa55401febaca4b4042c2a58681e7032d5b38a2bee6298c5d16ba5f6b91d04cdbf6482b4376d789b7a35cc3b33d597627bdf2'}) , {}. Вызов из модуля common.utils
2023-07-16 10:58:40,704 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777)>,) , {}. Вызов из модуля common.utils
2023-07-16 10:58:40,705 DEBUG (core.py) Getting data from client exception
Traceback (most recent call last):
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 77, in run
    self.parse_client_message(get_message(client_with_message),
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 64, in checker
    return func(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 155, in parse_client_message
    self.authorize_user(message, client)
  File "/home/aliya/PycharmProjects/client-server1/server/core.py", line 307, in authorize_user
    ans = get_message(sock)
  File "/home/aliya/PycharmProjects/client-server1/common/decos.py", line 23, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/aliya/PycharmProjects/client-server1/common/utils.py", line 22, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-16 10:58:40,726 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f801ecf3c40> отключился от сервера
2023-07-16 11:20:03,120 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 11:20:03,121 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 11:20:03,121 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-16 11:20:03,122 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 11:20:03,235 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 11:20:24,477 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 11:20:24,478 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 11:20:24,478 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['server.py']
2023-07-16 11:20:24,479 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 11:20:24,581 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 11:20:40,155 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 38320)
2023-07-16 11:20:41,044 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 38328)
2023-07-16 11:20:41,044 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 38320)>,) , {}. Вызов из модуля common.utils
2023-07-16 11:20:41,045 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689488440.1690807, 'user': {'account_name': 'test1'}}
2023-07-16 11:20:41,045 DEBUG (core.py) Start auth process for {'account_name': 'test1'}
2023-07-16 11:20:41,050 DEBUG (core.py) Correct username, starting passwd check
2023-07-16 11:20:41,052 DEBUG (core.py) Auth message = {'response': 511, 'bin': '99eef535b6f1dc6e4ca1424ab8a874dbc8ee30e642bbd548287b4c3f994801624b4ff5bdb2521600d4988a539c7f8bbed87892f88ac11f5047a67540cc28f791'}
2023-07-16 11:20:41,052 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 38320)>, {'response': 511, 'bin': '99eef535b6f1dc6e4ca1424ab8a874dbc8ee30e642bbd548287b4c3f994801624b4ff5bdb2521600d4988a539c7f8bbed87892f88ac11f5047a67540cc28f791'}) , {}. Вызов из модуля common.utils
2023-07-16 11:20:41,053 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 38320)>,) , {}. Вызов из модуля common.utils
2023-07-16 11:20:41,053 DEBUG (decos.py) Была вызвана функция send_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 38320)>, {'response': 200}) , {}. Вызов из модуля common.utils
2023-07-16 11:43:44,886 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 11:43:44,886 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 11:43:44,886 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-16 11:43:44,887 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 11:43:44,978 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 11:44:02,736 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 11:44:02,737 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 11:44:02,737 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['server.py']
2023-07-16 11:44:02,738 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 11:44:02,825 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 11:44:19,155 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 43464)
2023-07-16 11:44:20,078 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 43468)
2023-07-16 11:44:20,078 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 43464)>,) , {}. Вызов из модуля common.utils
2023-07-16 11:44:20,078 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689489859.18992, 'user': {'account_name': 'test1'}}
2023-07-16 11:44:20,096 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f6c58af8580> отключился от сервера
2023-07-16 11:45:56,576 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 11:45:56,577 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 11:45:56,578 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['server.py']
2023-07-16 11:45:56,579 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 11:45:56,693 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 11:46:06,728 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 50252)
2023-07-16 11:46:23,429 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 47486)
2023-07-16 11:46:23,430 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 50252)>,) , {}. Вызов из модуля common.utils
2023-07-16 11:46:23,430 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689489966.7417316, 'user': {'account_name': 'test2'}}
2023-07-16 11:46:23,437 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7fddad1f3c40> отключился от сервера
2023-07-16 11:51:47,598 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 11:51:47,599 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 11:51:47,599 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['server.py']
2023-07-16 11:51:47,601 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 11:51:47,746 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 11:51:57,033 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 40630)
2023-07-16 11:52:08,023 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 34350)
2023-07-16 11:52:08,023 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 40630)>,) , {}. Вызов из модуля common.utils
2023-07-16 11:52:08,024 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689490317.050419, 'user': {'account_name': 'test1'}}
2023-07-16 11:52:08,042 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f382d4b73a0> отключился от сервера
2023-07-16 11:53:18,399 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 11:53:18,400 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 11:53:18,400 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['server.py']
2023-07-16 11:53:18,401 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 11:53:18,491 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 11:53:36,512 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 36186)
2023-07-16 11:53:37,168 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 36188)
2023-07-16 11:53:37,168 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 36186)>,) , {}. Вызов из модуля common.utils
2023-07-16 11:53:37,169 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689490416.5419836, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqZwvV2c2l8GjJZTyFwgE\nWtbsrRrtKb9lKhSzqeKHq7z6WJUjHGOAFTCq5E9n71uRZP7AetM0/3xvBxQbOeCo\nfdBio9IU2irdWVMilCH7ZiXvFzOzdU4PzgTO2trIhId3RAWM2lsZfRuTmhPhwyTe\ngH01AgEnqcTKwLt8No1AENmeXGJyr1jttIJb5XXrXGjEv4wVOKuaEJGH97U5PAkR\ni2/I0DflNo2xfbV/BF2zQO0x2LGjvv9JDoceYbrbSipFX1GL0bp0ToS4MCtSTxm+\nNNum/ahFSw3G+EoBJhK2o0eFa/XPRZoceHTb53aJMDOgpcHt2FjKkLDyEsLMCKig\njQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 11:53:37,187 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7fb3bb9b2380> отключился от сервера
2023-07-16 14:55:52,316 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 14:55:52,343 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 14:55:52,343 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['server.py']
2023-07-16 14:55:52,345 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 14:55:52,854 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 14:56:58,785 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 59844)
2023-07-16 14:56:58,801 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 59854)
2023-07-16 14:58:01,233 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 54702)
2023-07-16 14:58:01,234 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59844)>,) , {}. Вызов из модуля common.utils
2023-07-16 14:58:01,234 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689501418.8206346, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmj0J1CkEDApGcAQ+CMvt\nIzsaR8gg90uEoIAB0bXNHphsuAx+Ck6of8/9ThLamT33C4soWlGkZqcHBtKcq+P+\nM//ucDlc8TGuQ2dlJfNyo1pb+t2d0piTi2EYgdehiWLerp31eAuB/OdcrEvxEnRt\np2roShLZAaqClU8pytOXzKQ+w13QbMUkOtLm4BcB57PUlZICwAGPZ3BLA7eFJETS\nNBDnceKdY26rzSX12NSbY4FM6I6yteCMY9KCVlPHc30Vj4T0TVDyQGQob94d2/WQ\nC6JQ86j/MM8BqlDo6Y0VqcthmqM8V2gsnNTVDgNL6PraM79RNdUJtTOIQm+G/fDy\n3QIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 14:58:01,237 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f49597579a0> отключился от сервера
2023-07-16 14:58:01,238 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=30, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59854)>,) , {}. Вызов из модуля common.utils
2023-07-16 14:58:01,238 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689501418.8269215, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 14:58:01,240 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f49597bdd80> отключился от сервера
2023-07-16 14:58:01,246 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 54712)
2023-07-16 15:11:43,458 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 15:11:43,458 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 15:11:43,458 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-16 15:11:43,459 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 15:11:43,523 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 15:12:07,730 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 58894)
2023-07-16 15:27:29,583 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 15:27:29,584 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 15:27:29,584 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['server.py']
2023-07-16 15:27:29,584 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 15:27:29,666 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 15:27:44,205 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 15:27:44,205 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 15:27:44,205 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['server.py']
2023-07-16 15:27:44,206 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 15:27:44,384 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 15:27:52,569 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 45920)
2023-07-16 15:27:52,581 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 45932)
2023-07-16 15:28:48,547 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 15:28:48,548 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 15:28:48,548 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-16 15:28:48,549 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 15:28:48,670 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 15:29:03,244 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 36578)
2023-07-16 15:32:33,302 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 15:32:33,303 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 15:32:33,303 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-16 15:32:33,304 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 15:32:33,381 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 15:33:24,713 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 55364)
2023-07-16 15:42:50,746 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 46768)
2023-07-16 15:42:50,747 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55364)>,) , {}. Вызов из модуля common.utils
2023-07-16 15:42:50,747 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689503604.7478666, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 15:42:50,771 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f74961f32e0> отключился от сервера
2023-07-16 15:55:32,470 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 52414)
2023-07-16 15:55:32,471 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 46768)>,) , {}. Вызов из модуля common.utils
2023-07-16 15:55:32,471 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689504170.7860744, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 15:55:32,472 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f74961f3520> отключился от сервера
2023-07-16 16:00:06,648 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 34218)
2023-07-16 16:00:06,648 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52414)>,) , {}. Вызов из модуля common.utils
2023-07-16 16:00:06,648 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689504932.4841805, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 16:00:06,650 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f7495de0a60> отключился от сервера
2023-07-16 16:00:46,604 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 55582)
2023-07-16 16:00:46,604 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 34218)>,) , {}. Вызов из модуля common.utils
2023-07-16 16:00:46,604 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689505206.6710963, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 16:00:46,607 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f7495db5900> отключился от сервера
2023-07-16 16:08:49,063 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 56678)
2023-07-16 16:08:49,063 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55582)>,) , {}. Вызов из модуля common.utils
2023-07-16 16:08:49,064 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689505246.624197, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 16:08:49,068 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f74961f3520> отключился от сервера
2023-07-16 16:09:46,617 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 33654)
2023-07-16 16:09:46,617 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 56678)>,) , {}. Вызов из модуля common.utils
2023-07-16 16:09:46,617 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689505729.0952342, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 16:09:46,619 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f74961f32e0> отключился от сервера
2023-07-16 16:27:45,022 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 43270)
2023-07-16 16:27:45,023 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 33654)>,) , {}. Вызов из модуля common.utils
2023-07-16 16:27:45,023 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689505786.6338048, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 16:27:45,027 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f7495db5900> отключился от сервера
2023-07-16 16:53:32,207 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 48158)
2023-07-16 16:53:32,208 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 43270)>,) , {}. Вызов из модуля common.utils
2023-07-16 16:53:32,208 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689506865.0351422, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 16:53:32,212 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7f74961f3520> отключился от сервера
2023-07-16 17:19:37,124 DEBUG (decos.py) Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2023-07-16 17:19:37,125 DEBUG (decos.py) Была вызвана функция create_arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2023-07-16 17:19:37,125 DEBUG (server.py) Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-16 17:19:37,130 DEBUG (server.py) Аргументы успешно загружены
2023-07-16 17:19:37,282 INFO (core.py) Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 17:20:01,940 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 33018)
2023-07-16 17:21:49,326 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 59120)
2023-07-16 17:21:49,326 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 33018)>,) , {}. Вызов из модуля common.utils
2023-07-16 17:21:49,327 INFO (utils.py) b'{"action": "presence", "time": 1689510001.975867, "user": {"account_name": "test1", "pubkey": "-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\\ncQIDAQAB\\n-----END PUBLIC KEY-----"}}'
2023-07-16 17:21:49,327 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689510001.975867, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 17:21:49,351 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7fd7f56b40a0> отключился от сервера
2023-07-16 17:27:01,049 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 57836)
2023-07-16 17:27:01,049 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59120)>,) , {}. Вызов из модуля common.utils
2023-07-16 17:27:01,049 INFO (utils.py) b'{"action": "presence", "time": 1689510109.3652792, "user": {"account_name": "test1", "pubkey": "-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\\ncQIDAQAB\\n-----END PUBLIC KEY-----"}}'
2023-07-16 17:27:01,050 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689510109.3652792, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 17:27:01,052 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7fd7f56b5f60> отключился от сервера
2023-07-16 17:34:27,235 INFO (core.py) Установлено соедение с клиентом: ('127.0.0.1', 49620)
2023-07-16 17:34:27,236 DEBUG (decos.py) Была вызвана функция get_message c параметрами (<socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57836)>,) , {}. Вызов из модуля common.utils
2023-07-16 17:34:27,236 INFO (utils.py) b'{"action": "presence", "time": 1689510421.067021, "user": {"account_name": "test1", "pubkey": "-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\\ncQIDAQAB\\n-----END PUBLIC KEY-----"}}'
2023-07-16 17:34:27,236 DEBUG (core.py) Разбор сообщения от клиента: {'action': 'presence', 'time': 1689510421.067021, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 17:34:27,241 INFO (core.py) Клиент <built-in method getpeername of socket object at 0x7fd7f56b6200> отключился от сервера
2023-07-16 18:23:49,583 DEBUG server.py Инициализация парсера аргументов командной строки: ['/home/aliya/PycharmProjects/client-server1/server.py']
2023-07-16 18:23:49,584 DEBUG server.py Аргументы успешно загружены
2023-07-16 18:23:49,650 INFO core.py Запущен сервер, порт для подключений: 7777, адрес: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-16 18:28:39,046 INFO core.py Установлено соедение с клиентом: ('127.0.0.1', 52066)
2023-07-16 18:29:28,743 INFO core.py Установлено соедение с клиентом: ('127.0.0.1', 53472)
2023-07-16 18:29:28,743 DEBUG core.py Разбор сообщения от клиента: {'action': 'presence', 'time': 1689514119.0822923, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 18:29:28,749 INFO core.py Клиент <built-in method getpeername of socket object at 0x7f372e263ac0> отключился от сервера
2023-07-16 18:30:42,739 INFO core.py Установлено соедение с клиентом: ('127.0.0.1', 49070)
2023-07-16 18:30:42,740 DEBUG core.py Разбор сообщения от клиента: {'action': 'presence', 'time': 1689514168.753105, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 18:30:42,745 INFO core.py Клиент <built-in method getpeername of socket object at 0x7f372e261120> отключился от сервера
2023-07-16 18:31:18,412 INFO core.py Установлено соедение с клиентом: ('127.0.0.1', 33188)
2023-07-16 18:31:18,413 DEBUG core.py Разбор сообщения от клиента: {'action': 'presence', 'time': 1689514242.7730355, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwZazpuBSzagZdxCwXUkG\nu8JvnUnhn+59OqgRmMNd8RorV5n00DVhW813+YUnlBrELnj6PmDBw3+Wo8sSM5u/\nQjMfIIiKERurrAVqxzmW6dlF0kwjUXXV89x8ZJM88XCkq5E1KS2/pMMA4fIwMLMS\n0JdPSGJTC/HDTqFUo/ozLtLGMajNED8VMFPypJBUmIo/beg0arqQxrguAP71bGgV\nqGKCxt+XZWMjja+jLLCUFyiteisguR4+o9+Jadhzten/nefZeJzw+pJcnZZjxFtI\nu+XE77yzwtzrF8lLKOjmRL5tfPNBbfuBeMcSJQUtKN5eu832jxgyBFGWI9wfOncq\ncQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-16 18:31:18,419 INFO core.py Клиент <built-in method getpeername of socket object at 0x7f372e260a60> отключился от сервера
